name: prefnotifiers
description: Represents shared preferences as ValueNotifier objects. Reads and writes occur asynchronously in background.
version: 1.0.4
homepage: https://github.com/rtmigo/prefnotifiers

environment:
  # same as in shared preferences 2.0.5 2021-03-25:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

