name: prefnotifiers
description: Use individual shared preferences as ValueNotifier objects.
version: 0.0.1
homepage: https://github.com/rtmigo/prefnotifiers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # nothing here :)
