name: prefnotifiers
description: Represents shared preferences as ValueNotifier objects. Reads and writes occur asynchronously in background.
version: 1.0.2-beta
homepage: https://github.com/rtmigo/prefnotifiers

environment:
  # shared preferences 2021-03-25:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

  #sdk: ">=2.12.0-beta <3.0.0"
  #flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.5

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

