# Based on:
# https://dev.to/emilioschepis/adding-continuous-integration-to-a-flutter-project-with-github-actions-48p1
# https://poetryincode.dev/testing-dart-packages-with-github-actions

name: ci test

on:
  push:
    branches: [ dev master ]

jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Download Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Init Flutter and install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    file: coverage/lcov.info


#jobs:
#  workflow:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#            - name: Install Flutter
#            uses: subosito/flutter-action@v1.3.2
#            - name: Install app dependencies
#              run: flutter pub get

      #- uses: actions/checkout@v2
      #- name: Download Flutter
       # run: |
      #    git clone https://github.com/flutter/flutter.git -b stable --depth 1
      #    echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      #- name: Init Flutter
      #  run: |
      #    flutter --version
      ##    flutter doctor --android-licenses
      #    echo "Flutter initialized"


      #    flutter --version
       #   flutter doctor --android-licenses
       #   echo "Flutter setup complete"
      #- name: Run Checks # (3)
      #  run: |
      #    flutter pub get
      #    flutter format lib/** --set-exit-if-changed
      #    flutter analyze --no-pub
      #    flutter test --no-pub